/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vds.UI.SystemAdmin;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vds.Database.DBConnection;
import vds.UI.Distributor.DistributorMainFrame;

/**
 *
 * @author jigne
 */
public class ManageNGOForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageNGOForm
     */
    DBConnection conn;
    Connection sqlConn;
    Resultset rs;
    PreparedStatementWrapper pst = null;
    String ngoAdminEmail;

    public ManageNGOForm() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DBConnection();
        sqlConn = DBConnection.connectDB();
        if (conn == null) {
            JOptionPane.showMessageDialog(this,
                    "Database Error", "Failure", JOptionPane.ERROR_MESSAGE);
        } else {
            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("SELECT * from `vds`.`user` WHERE Role=?");
                pst.setString(1, "NgoAdmin");
                ResultSet rs = pst.executeQuery();
                ArrayList<String> NgoAdmins = new ArrayList<String>();
                while (rs.next()) {
                    NgoAdmins.add(rs.getString(2));
                    System.out.println(rs.getString(2));
                }
                ngoAdminDropDown.setModel(new DefaultComboBoxModel<String>(NgoAdmins.toArray(new String[0])));
            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();
        AddNGOPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        countryField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ngoNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ngoAdminDropDown = new javax.swing.JComboBox<>();
        AddNGOButton = new javax.swing.JButton();
        DeleteNGOPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deleteByCombo = new javax.swing.JComboBox<>();
        deleteBy = new javax.swing.JTextField();
        DeleteNGOButton = new javax.swing.JButton();
        ViewNGOPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storageTable = new javax.swing.JTable();
        UpdateNGOPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        findByCombo = new javax.swing.JComboBox<>();
        findBy = new javax.swing.JTextField();
        FindNGOUpdate = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ngoContact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ngoEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ngoLocation = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ngoCity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ngoState = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ngoCountry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ngoName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        UpdateNGOButton = new javax.swing.JButton();
        ngoAdmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE NGO");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(35, 35, 35)
                .addComponent(jButton4)
                .addGap(40, 40, 40)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ParentPanel.setLayout(new java.awt.CardLayout());

        AddNGOPanel.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD NGO FORM");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(97, 212, 195));
        jLabel5.setText("CONTACT:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(97, 212, 195));
        jLabel6.setText("EMAIL:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(97, 212, 195));
        jLabel7.setText("Location:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 212, 195));
        jLabel8.setText("CITY:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(97, 212, 195));
        jLabel9.setText("STATE:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(97, 212, 195));
        jLabel10.setText("COUNTRY:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(97, 212, 195));
        jLabel3.setText("NGO NAME:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(97, 212, 195));
        jLabel11.setText("ADMIN:");

        ngoAdminDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        ngoAdminDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngoAdminDropDownActionPerformed(evt);
            }
        });

        AddNGOButton.setText("ADD");
        AddNGOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNGOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddNGOPanelLayout = new javax.swing.GroupLayout(AddNGOPanel);
        AddNGOPanel.setLayout(AddNGOPanelLayout);
        AddNGOPanelLayout.setHorizontalGroup(
            AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addGroup(AddNGOPanelLayout.createSequentialGroup()
                .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNGOPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ngoNameField)
                            .addComponent(ngoAdminDropDown, 0, 126, Short.MAX_VALUE)))
                    .addGroup(AddNGOPanelLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(AddNGOButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddNGOPanelLayout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(contactField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(cityField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(stateField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(countryField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
        AddNGOPanelLayout.setVerticalGroup(
            AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNGOPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ngoNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ngoAdminDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(AddNGOButton)
                .addGap(39, 39, 39))
            .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddNGOPanelLayout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(AddNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(145, Short.MAX_VALUE)))
        );

        ParentPanel.add(AddNGOPanel, "card2");

        DeleteNGOPanel.setBackground(new java.awt.Color(0, 0, 204));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(97, 212, 195));
        jLabel14.setText("DELETE NGO");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(97, 212, 195));
        jLabel15.setText("SELECT:");

        deleteByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Email" }));

        DeleteNGOButton.setText("DELETE");
        DeleteNGOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteNGOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteNGOPanelLayout = new javax.swing.GroupLayout(DeleteNGOPanel);
        DeleteNGOPanel.setLayout(DeleteNGOPanelLayout);
        DeleteNGOPanelLayout.setHorizontalGroup(
            DeleteNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteNGOPanelLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(DeleteNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteNGOPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBy, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteNGOPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteNGOPanelLayout.createSequentialGroup()
                        .addComponent(DeleteNGOButton)
                        .addGap(288, 288, 288))))
        );
        DeleteNGOPanelLayout.setVerticalGroup(
            DeleteNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteNGOPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(DeleteNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addComponent(DeleteNGOButton)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        ParentPanel.add(DeleteNGOPanel, "card3");

        ViewNGOPanel.setBackground(new java.awt.Color(0, 0, 102));

        storageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NGO Name", "Contact", "Email", "Location", "City", "State", "Country", "Admin"
            }
        ));
        jScrollPane1.setViewportView(storageTable);

        javax.swing.GroupLayout ViewNGOPanelLayout = new javax.swing.GroupLayout(ViewNGOPanel);
        ViewNGOPanel.setLayout(ViewNGOPanelLayout);
        ViewNGOPanelLayout.setHorizontalGroup(
            ViewNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        ViewNGOPanelLayout.setVerticalGroup(
            ViewNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        ParentPanel.add(ViewNGOPanel, "card4");

        UpdateNGOPanel.setBackground(new java.awt.Color(0, 0, 204));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(97, 212, 195));
        jLabel17.setText("FIND BY-");

        findByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Email" }));

        FindNGOUpdate.setText("FIND");
        FindNGOUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindNGOUpdateActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(97, 212, 195));
        jLabel18.setText("UPDATE NGO FORM");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(97, 212, 195));
        jLabel12.setText("CONTACT:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(97, 212, 195));
        jLabel13.setText("EMAIL:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(97, 212, 195));
        jLabel19.setText("Location:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(97, 212, 195));
        jLabel20.setText("CITY:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(97, 212, 195));
        jLabel21.setText("STATE:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(97, 212, 195));
        jLabel22.setText("COUNTRY:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 212, 195));
        jLabel4.setText("NGO NAME:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(97, 212, 195));
        jLabel23.setText("ADMIN:");

        UpdateNGOButton.setText("UPDATE");
        UpdateNGOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNGOButtonActionPerformed(evt);
            }
        });

        ngoAdmin.setText("jTextField1");
        ngoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngoAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateNGOPanelLayout = new javax.swing.GroupLayout(UpdateNGOPanel);
        UpdateNGOPanel.setLayout(UpdateNGOPanelLayout);
        UpdateNGOPanelLayout.setHorizontalGroup(
            UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateNGOPanelLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateNGOPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(findByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findBy, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FindNGOUpdate)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateNGOPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateNGOPanelLayout.createSequentialGroup()
                        .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel4)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ngoCountry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(ngoState, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngoCity)
                            .addComponent(ngoLocation)
                            .addComponent(ngoEmail)
                            .addComponent(ngoContact)
                            .addComponent(ngoName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(ngoAdmin))
                        .addGap(212, 212, 212))))
            .addGroup(UpdateNGOPanelLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(UpdateNGOButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        UpdateNGOPanelLayout.setVerticalGroup(
            UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateNGOPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(findByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindNGOUpdate))
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addGap(28, 28, 28)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateNGOPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ngoContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ngoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ngoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ngoCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ngoState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ngoCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateNGOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ngoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UpdateNGOButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ParentPanel.add(UpdateNGOPanel, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SysAdminMainFrame sa = new SysAdminMainFrame();
        ManageNGOForm mc = new ManageNGOForm();
        sa.setVisible(true);
        mc.setVisible(false);
        super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(AddNGOPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(DeleteNGOPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        PreparedStatement pst;
        while (storageTable.getRowCount() > 0) {
            ((DefaultTableModel) storageTable.getModel()).removeRow(0);
        }
        try {

            pst = sqlConn.prepareStatement("SELECT `Name`, `Contact`, `Email`,  `City`, `State`, `Country`, `Admin`, `AdminEmail`, `Location` from `ngo` ");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String Name = rs.getString(1);
                String contact = rs.getString(2);
                String email = rs.getString(3);
                String city = rs.getString(4);
                String state = rs.getString(5);
                String country = rs.getString(6);
                String admin = rs.getString(7);
                String adminEmail = rs.getString(8);
                String Location = rs.getString(9);

                Object[] rowData = new Object[]{Name, contact, email, Location, city, state, country, admin, adminEmail};
                ((DefaultTableModel) storageTable.getModel()).addRow(rowData);
            }

            //.setModel(new DefaultComboBoxModel<String>(SupplierAdmins.toArray(new String[0])));
        } catch (SQLException ex) {
            Logger.getLogger(DistributorMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(ViewNGOPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(UpdateNGOPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AddNGOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNGOButtonActionPerformed
        // TODO add your handling code here:
        String ngoName = ngoNameField.getText();
        String email = emailField.getText();
        String contact = contactField.getText();
        String street = location.getText();
        String city = cityField.getText();
        String state = stateField.getText();
        String country = countryField.getText();
        //String date = dateFormat.format(dobDate.getDate());
        String emailPattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        String ngoAdmin = String.valueOf(ngoAdminDropDown.getSelectedItem());
        String phonePattern = "(0|91)?[6-9][0-9]{9}";

        String namePattern = "[a-zA-Z_ ]+";
        PreparedStatement pst;
        try {
            pst = sqlConn.prepareStatement("SELECT Email from `vds`.`user` WHERE fName =?");
            pst.setString(1, ngoAdmin);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                ngoAdminEmail = rs.getString(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (ngoName.isEmpty() || email.isEmpty() || contact.isEmpty() || street.isEmpty() || city.isEmpty() || state.isEmpty() || country.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter All Details", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!ngoName.matches(namePattern)) {
            JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this, "Enter a Valid Email", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!contact.matches(phonePattern)) {
            JOptionPane.showMessageDialog(this, "Enter a Valid Phone Number", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                PreparedStatement pst1 = sqlConn.prepareStatement("INSERT INTO `vds`.`ngo` (Name, Contact, Email, City, State, Country, Admin, AdminEmail,Location) VALUES (?, ?, ? ,?,?, ?, ?, ?, ?);");
                pst1.setString(1, ngoName);
                pst1.setString(2, contact);
                pst1.setString(3, email);
                pst1.setString(4, city);
                pst1.setString(5, state);
                pst1.setString(6, country);
                pst1.setString(7, ngoAdmin);
                pst1.setString(8, ngoAdminEmail);
                pst1.setString(9, location.getText());
                
                pst1.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "NGO Added Successfully", "Welcome",
                    JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_AddNGOButtonActionPerformed

    private void ngoAdminDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngoAdminDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngoAdminDropDownActionPerformed

    private void DeleteNGOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteNGOButtonActionPerformed
        String findUpdate = deleteByCombo.getSelectedItem().toString();
        if (findUpdate.matches("ID")) {

            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("Delete from ngo Where NgoID = ?");
                pst.setString(1, deleteBy.getText());
                pst.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

//                clinicAdminDropDown.setModel(new DefaultComboBoxModel<String>(clinicAdmins.toArray(new String[0])));
        } else {
            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("DELETE from ngo Where Email = ?");
                pst.setString(1, deleteBy.getText());
                pst.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_DeleteNGOButtonActionPerformed

    private void FindNGOUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindNGOUpdateActionPerformed
        String findUpdate = findByCombo.getSelectedItem().toString();
        if (findUpdate.matches("ID")) {

            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("SELECT Name,Contact,Email,City,State,Country,Admin,Location from ngo Where NgoID = ?");
                pst.setString(1, findBy.getText());
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    ngoName.setText(rs.getString(1));
                    ngoContact.setText(rs.getString(2));
                    ngoEmail.setText(rs.getString(3));
                    ngoCity.setText(rs.getString(4));
                    ngoState.setText(rs.getString(5));
                    ngoCountry.setText(rs.getString(6));
                    ngoAdmin.setText(rs.getString(7));
                    ngoLocation.setText(rs.getString(8));

                }

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }

//                clinicAdminDropDown.setModel(new DefaultComboBoxModel<String>(clinicAdmins.toArray(new String[0])));
        } else {
            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("SELECT Name,Contact,Email,City,State,Country,Admin,Location from ngo Where Email = ?");
                pst.setString(1, findBy.getText());
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    ngoName.setText(rs.getString(1));
                    ngoContact.setText(rs.getString(2));
                    ngoEmail.setText(rs.getString(3));
                    ngoCity.setText(rs.getString(4));
                    ngoState.setText(rs.getString(5));
                    ngoCountry.setText(rs.getString(6));
                    ngoAdmin.setText(rs.getString(7));
                    ngoLocation.setText(rs.getString(8));

                }

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Distributor Delete Successfully", "Welcome",
                    JOptionPane.INFORMATION_MESSAGE);
        }// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_FindNGOUpdateActionPerformed

    private void ngoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngoAdminActionPerformed

    private void UpdateNGOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNGOButtonActionPerformed
   PreparedStatement pst;
        try {
            pst = sqlConn.prepareStatement("UPDATE ngo SET Name = ?,Contact = ?,Email = ?,City =? ,State = ?,Country =?,Admin=?,Location=?   Where NgoID = ?");
            pst.setString(1, ngoName.getText());
            pst.setString(2, ngoContact.getText());
            pst.setString(3, ngoEmail.getText());
            pst.setString(4, ngoCity.getText());
            pst.setString(5, ngoState.getText());
            pst.setString(6, ngoCountry.getText());
            pst.setString(7, ngoAdmin.getText());
            pst.setString(8, ngoLocation.getText());
            pst.setString(9, findBy.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "NGO Updated Successfully", "Welcome",
                    JOptionPane.INFORMATION_MESSAGE);
            ngoName.setText("");
            ngoContact.setText("");
            ngoEmail.setText("");
            ngoCity.setText("");
            ngoState.setText("");
            ngoCountry.setText("");
            ngoAdmin.setText("");
            ngoLocation.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateNGOButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageNGOForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageNGOForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageNGOForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageNGOForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageNGOForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNGOButton;
    private javax.swing.JPanel AddNGOPanel;
    private javax.swing.JButton DeleteNGOButton;
    private javax.swing.JPanel DeleteNGOPanel;
    private javax.swing.JButton FindNGOUpdate;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton UpdateNGOButton;
    private javax.swing.JPanel UpdateNGOPanel;
    private javax.swing.JPanel ViewNGOPanel;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField countryField;
    private javax.swing.JTextField deleteBy;
    private javax.swing.JComboBox<String> deleteByCombo;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField findBy;
    private javax.swing.JComboBox<String> findByCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField ngoAdmin;
    private javax.swing.JComboBox<String> ngoAdminDropDown;
    private javax.swing.JTextField ngoCity;
    private javax.swing.JTextField ngoContact;
    private javax.swing.JTextField ngoCountry;
    private javax.swing.JTextField ngoEmail;
    private javax.swing.JTextField ngoLocation;
    private javax.swing.JTextField ngoName;
    private javax.swing.JTextField ngoNameField;
    private javax.swing.JTextField ngoState;
    private javax.swing.JTextField stateField;
    private javax.swing.JTable storageTable;
    // End of variables declaration//GEN-END:variables
}
