/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vds.UI.SystemAdmin;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vds.Database.DBConnection;
import vds.UI.Distributor.DistributorMainFrame;

/**
 *
 * @author jigne
 */
public class ManageHospitalForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageHospitalForm
     */
    DBConnection conn;
    Connection sqlConn;
    Resultset rs;
    PreparedStatementWrapper pst = null;
    String hEmail;

    public ManageHospitalForm() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DBConnection();
        sqlConn = DBConnection.connectDB();
        if (conn == null) {
            JOptionPane.showMessageDialog(this,
                    "Database Error", "Failure", JOptionPane.ERROR_MESSAGE);
        } else {
            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("SELECT * from `vds`.`user` WHERE Role=?");
                pst.setString(1, "HospitalAdmin");
                ResultSet rs = pst.executeQuery();
                ArrayList<String> hospitalAdmins = new ArrayList<String>();
                while (rs.next()) {
                    hospitalAdmins.add(rs.getString(2));
                    System.out.println(rs.getString(2));
                }
                hospitalAdminDropDown.setModel(new DefaultComboBoxModel<String>(hospitalAdmins.toArray(new String[0])));
            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();
        AddHospitalPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hospitalNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        countryField = new javax.swing.JTextField();
        AddHospitalButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hospitalAdminDropDown = new javax.swing.JComboBox<>();
        DeleteHospitalPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deleteByCombo = new javax.swing.JComboBox<>();
        deleteBy = new javax.swing.JTextField();
        DeleteHospitalButton = new javax.swing.JButton();
        ViewHospitalsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storageTable = new javax.swing.JTable();
        UpdateHospitalsPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        findByCombo = new javax.swing.JComboBox<>();
        findBy = new javax.swing.JTextField();
        FindHospitalUpdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        hosContact = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        hosEmail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        hosLocation = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        hosCity = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        hosState = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        hosCountry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        hosName = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        UpdateHospitalButton = new javax.swing.JButton();
        hosAdmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("MANAGE HOSPITAL");

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(39, 39, 39)
                .addComponent(jButton3)
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addGap(41, 41, 41)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ParentPanel.setLayout(new java.awt.CardLayout());

        AddHospitalPanel.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD HOSPITAL FORM");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(97, 212, 195));
        jLabel3.setText("HOSPITAL NAME:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(97, 212, 195));
        jLabel5.setText("CONTACT:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(97, 212, 195));
        jLabel6.setText("EMAIL:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(97, 212, 195));
        jLabel7.setText("Location:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 212, 195));
        jLabel8.setText("CITY:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(97, 212, 195));
        jLabel9.setText("STATE:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(97, 212, 195));
        jLabel10.setText("COUNTRY:");

        AddHospitalButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddHospitalButton.setText("ADD");
        AddHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddHospitalButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(97, 212, 195));
        jLabel11.setText("ADMIN:");

        hospitalAdminDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));

        javax.swing.GroupLayout AddHospitalPanelLayout = new javax.swing.GroupLayout(AddHospitalPanel);
        AddHospitalPanel.setLayout(AddHospitalPanelLayout);
        AddHospitalPanelLayout.setHorizontalGroup(
            AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddHospitalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddHospitalButton)
                .addGap(285, 285, 285))
            .addGroup(AddHospitalPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contactField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(cityField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(stateField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(countryField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(hospitalAdminDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddHospitalPanelLayout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(jLabel3)
                    .addGap(18, 18, 18)
                    .addComponent(hospitalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );
        AddHospitalPanelLayout.setVerticalGroup(
            AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddHospitalPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(90, 90, 90)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(hospitalAdminDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(AddHospitalButton)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddHospitalPanelLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addGroup(AddHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(hospitalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        ParentPanel.add(AddHospitalPanel, "card2");

        DeleteHospitalPanel.setBackground(new java.awt.Color(0, 0, 204));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(97, 212, 195));
        jLabel14.setText("DELETE HOSPITAL");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(97, 212, 195));
        jLabel15.setText("SELECT:");

        deleteByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Email" }));

        DeleteHospitalButton.setText("DELETE");
        DeleteHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteHospitalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteHospitalPanelLayout = new javax.swing.GroupLayout(DeleteHospitalPanel);
        DeleteHospitalPanel.setLayout(DeleteHospitalPanelLayout);
        DeleteHospitalPanelLayout.setHorizontalGroup(
            DeleteHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteHospitalPanelLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(DeleteHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteHospitalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBy, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteHospitalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteHospitalPanelLayout.createSequentialGroup()
                        .addComponent(DeleteHospitalButton)
                        .addGap(288, 288, 288))))
        );
        DeleteHospitalPanelLayout.setVerticalGroup(
            DeleteHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteHospitalPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(DeleteHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addComponent(DeleteHospitalButton)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        ParentPanel.add(DeleteHospitalPanel, "card3");

        ViewHospitalsPanel.setBackground(new java.awt.Color(0, 0, 102));

        storageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Contact", "Email", "Street", "City", "State", "Country", "Admin"
            }
        ));
        jScrollPane1.setViewportView(storageTable);

        javax.swing.GroupLayout ViewHospitalsPanelLayout = new javax.swing.GroupLayout(ViewHospitalsPanel);
        ViewHospitalsPanel.setLayout(ViewHospitalsPanelLayout);
        ViewHospitalsPanelLayout.setHorizontalGroup(
            ViewHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewHospitalsPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        ViewHospitalsPanelLayout.setVerticalGroup(
            ViewHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        ParentPanel.add(ViewHospitalsPanel, "card4");

        UpdateHospitalsPanel.setBackground(new java.awt.Color(0, 0, 204));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(97, 212, 195));
        jLabel17.setText("FIND BY-");

        findByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Email" }));

        FindHospitalUpdate.setText("FIND");
        FindHospitalUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindHospitalUpdateActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(97, 212, 195));
        jLabel20.setText("CONTACT:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(97, 212, 195));
        jLabel21.setText("EMAIL:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(97, 212, 195));
        jLabel22.setText("Location:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(97, 212, 195));
        jLabel23.setText("CITY:");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(97, 212, 195));
        jLabel24.setText("STATE:");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(97, 212, 195));
        jLabel25.setText("COUNTRY:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADD HOSPITAL FORM");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(97, 212, 195));
        jLabel26.setText("HOSPITAL NAME:");

        hosName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosNameActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(97, 212, 195));
        jLabel27.setText("ADMIN:");

        UpdateHospitalButton.setText("UPDATE");
        UpdateHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateHospitalButtonActionPerformed(evt);
            }
        });

        hosAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateHospitalsPanelLayout = new javax.swing.GroupLayout(UpdateHospitalsPanel);
        UpdateHospitalsPanel.setLayout(UpdateHospitalsPanelLayout);
        UpdateHospitalsPanelLayout.setHorizontalGroup(
            UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateHospitalsPanelLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(findByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(findBy, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FindHospitalUpdate)
                .addGap(105, 105, 105))
            .addGroup(UpdateHospitalsPanelLayout.createSequentialGroup()
                .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateHospitalsPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hosName, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(hosAdmin)))
                    .addGroup(UpdateHospitalsPanelLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(UpdateHospitalButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UpdateHospitalsPanelLayout.createSequentialGroup()
                    .addGap(230, 230, 230)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24))
                    .addGap(18, 18, 18)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hosContact)
                        .addComponent(hosEmail)
                        .addComponent(hosLocation)
                        .addComponent(hosCity)
                        .addComponent(hosState)
                        .addComponent(hosCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addContainerGap(231, Short.MAX_VALUE)))
        );
        UpdateHospitalsPanelLayout.setVerticalGroup(
            UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateHospitalsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(findByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindHospitalUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(hosName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(hosAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(UpdateHospitalButton)
                .addGap(42, 42, 42))
            .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UpdateHospitalsPanelLayout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(hosContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(hosEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(hosLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(hosCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(hosState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(UpdateHospitalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(hosCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        ParentPanel.add(UpdateHospitalsPanel, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ParentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SysAdminMainFrame sa = new SysAdminMainFrame();
        ManageHospitalForm mp = new ManageHospitalForm();
        sa.setVisible(true);
        mp.setVisible(false);
        super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PreparedStatement pst;
        while (storageTable.getRowCount() > 0) {
            ((DefaultTableModel) storageTable.getModel()).removeRow(0);
        }
        try {

            pst = sqlConn.prepareStatement("SELECT `Name`, `Contact`, `Email`,  `City`, `State`, `Country`, `Admin`, `AdminEmail`, `Location` from `hospital` ");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String Name = rs.getString(1);
                String contact = rs.getString(2);
                String email = rs.getString(3);
                String city = rs.getString(4);
                String state = rs.getString(5);
                String country = rs.getString(6);
                String admin = rs.getString(7);
                String adminEmail = rs.getString(8);
                String Location = rs.getString(9);

                Object[] rowData = new Object[]{Name, contact, email, Location, city, state, country, admin, adminEmail};
                ((DefaultTableModel) storageTable.getModel()).addRow(rowData);
            }

            //.setModel(new DefaultComboBoxModel<String>(SupplierAdmins.toArray(new String[0])));
        } catch (SQLException ex) {
            Logger.getLogger(DistributorMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(ViewHospitalsPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(AddHospitalPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(DeleteHospitalPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ParentPanel.removeAll();
        ParentPanel.add(UpdateHospitalsPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void hosNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hosNameActionPerformed

    private void AddHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddHospitalButtonActionPerformed
        // TODO add your handling code here:
        String hospitalName = hospitalNameField.getText();
        String email = emailField.getText();
        String contact = contactField.getText();
        String street = location.getText();
        String city = cityField.getText();
        String state = stateField.getText();
        String country = countryField.getText();
        //String date = dateFormat.format(dobDate.getDate());
        String emailPattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        String phonePattern = "(0|91)?[6-9][0-9]{9}";

        String namePattern = "[a-zA-Z_ ]+";

        String hAdmin = String.valueOf(hospitalAdminDropDown.getSelectedItem());
        PreparedStatement pst;
        try {
            pst = sqlConn.prepareStatement("SELECT Email from `vds`.`user` WHERE fName =?");
            pst.setString(1, hAdmin);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                hEmail = rs.getString(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (hospitalName.isEmpty() || email.isEmpty() || contact.isEmpty() || street.isEmpty() || city.isEmpty() || state.isEmpty() || country.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter All Details", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!hospitalName.matches(namePattern)) {
            JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this, "Enter a Valid Email", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!contact.matches(phonePattern)) {
            JOptionPane.showMessageDialog(this, "Enter a Valid Phone Number", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                PreparedStatement pst1 = sqlConn.prepareStatement("INSERT INTO `vds`.`hospital` (Name, Contact, Email, City, State, Country, Admin, AdminEmail,Location) VALUES (?, ?, ?, ?, ?, ?, ?, ?,?);");
                pst1.setString(1, hospitalName);
                pst1.setString(2, contact);
                pst1.setString(3, email);
                pst1.setString(4, city);
                pst1.setString(5, state);
                pst1.setString(6, country);
                pst1.setString(7, hAdmin);
                pst1.setString(8, hEmail);
                pst1.setString(9, location.getText());
                pst1.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Hospital Added Successfully", "Welcome",
                    JOptionPane.INFORMATION_MESSAGE);
            hospitalNameField.setText("");
            emailField.setText("");
            contactField.setText("");
            cityField.setText("");
            stateField.setText("");
            countryField.setText("");
        }
    }//GEN-LAST:event_AddHospitalButtonActionPerformed

    private void FindHospitalUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindHospitalUpdateActionPerformed

        String findUpdate = findByCombo.getSelectedItem().toString();
        if (findUpdate.matches("ID")) {

            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("SELECT Name,Contact,Email,City,State,Country,Admin,Location from hospital Where HospitalID = ?");
                pst.setString(1, findBy.getText());
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    hosName.setText(rs.getString(1));
                    hosContact.setText(rs.getString(2));
                    hosEmail.setText(rs.getString(3));
                    hosCity.setText(rs.getString(4));
                    hosState.setText(rs.getString(5));
                    hosCountry.setText(rs.getString(6));
                    hosAdmin.setText(rs.getString(7));
                    hosLocation.setText(rs.getString(8));

                }

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }

//                clinicAdminDropDown.setModel(new DefaultComboBoxModel<String>(clinicAdmins.toArray(new String[0])));
        } else {
            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("SELECT Name,Contact,Email,City,State,Country,Admin,Location from distributor Where Email = ?");
                pst.setString(1, findBy.getText());
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    hosName.setText(rs.getString(1));
                    hosContact.setText(rs.getString(2));
                    hosEmail.setText(rs.getString(3));
                    hosCity.setText(rs.getString(4));
                    hosState.setText(rs.getString(5));
                    hosCountry.setText(rs.getString(6));
                    hosAdmin.setText(rs.getString(7));
                    hosLocation.setText(rs.getString(8));

                }

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Distributor Delete Successfully", "Welcome",
                    JOptionPane.INFORMATION_MESSAGE);
        }// TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_FindHospitalUpdateActionPerformed

    private void hosAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hosAdminActionPerformed

    private void DeleteHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteHospitalButtonActionPerformed
        String findUpdate = deleteByCombo.getSelectedItem().toString();
        if (findUpdate.matches("ID")) {

            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("Delete from hospital Where HospitalID = ?");
                pst.setString(1, deleteBy.getText());
                pst.executeUpdate();
                deleteBy.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

//                clinicAdminDropDown.setModel(new DefaultComboBoxModel<String>(clinicAdmins.toArray(new String[0])));
        } else {
            PreparedStatement pst;
            try {
                pst = sqlConn.prepareStatement("DELETE from hospital Where Email = ?");
                pst.setString(1, deleteBy.getText());
                pst.executeUpdate();
                deleteBy.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(ManageHospitalForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteHospitalButtonActionPerformed

    private void UpdateHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateHospitalButtonActionPerformed
        PreparedStatement pst;
        try {
            pst = sqlConn.prepareStatement("UPDATE hospital SET Name = ?,Contact = ?,Email = ?,City =? ,State = ?,Country =?,Admin=?,Location=?   Where HospitalID = ?");
            pst.setString(1, hosName.getText());
            pst.setString(2, hosContact.getText());
            pst.setString(3, hosEmail.getText());
            pst.setString(4, hosCity.getText());
            pst.setString(5, hosState.getText());
            pst.setString(6, hosCountry.getText());
            pst.setString(7, hosAdmin.getText());
            pst.setString(8, hosLocation.getText());
            pst.setString(9, findBy.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Hospital Updated Successfully", "Welcome",
                    JOptionPane.INFORMATION_MESSAGE);
            hosName.setText("");
            hosContact.setText("");
            hosEmail.setText("");
            hosCity.setText("");
            hosState.setText("");
            hosCountry.setText("");
            hosAdmin.setText("");
            hosLocation.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(ManageHospitalForm.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_UpdateHospitalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageHospitalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageHospitalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageHospitalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageHospitalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageHospitalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddHospitalButton;
    private javax.swing.JPanel AddHospitalPanel;
    private javax.swing.JButton DeleteHospitalButton;
    private javax.swing.JPanel DeleteHospitalPanel;
    private javax.swing.JButton FindHospitalUpdate;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton UpdateHospitalButton;
    private javax.swing.JPanel UpdateHospitalsPanel;
    private javax.swing.JPanel ViewHospitalsPanel;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField countryField;
    private javax.swing.JTextField deleteBy;
    private javax.swing.JComboBox<String> deleteByCombo;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField findBy;
    private javax.swing.JComboBox<String> findByCombo;
    private javax.swing.JTextField hosAdmin;
    private javax.swing.JTextField hosCity;
    private javax.swing.JTextField hosContact;
    private javax.swing.JTextField hosCountry;
    private javax.swing.JTextField hosEmail;
    private javax.swing.JTextField hosLocation;
    private javax.swing.JTextField hosName;
    private javax.swing.JTextField hosState;
    private javax.swing.JComboBox<String> hospitalAdminDropDown;
    private javax.swing.JTextField hospitalNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField stateField;
    private javax.swing.JTable storageTable;
    // End of variables declaration//GEN-END:variables
}
