/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vds.UI;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import vds.Business.Role.ClinicAdmin.ClinicAdmin;
import vds.Business.Role.DistributingManager.DistributingManager;
import vds.Business.Role.EnterpriseManager.EnterpriseManager;
import vds.Business.Role.HospitalAdmin.HospitalAdmin;
import vds.Business.Role.LogisticsManager.LogisticsManager;
import vds.Business.Role.NgoAdmin.NgoAdmin;
import vds.Business.Role.Patient.Patient;
import vds.Business.Role.SupplyManager.SupplyManager;
import vds.Business.Role.SystemAdmin;
import vds.Database.DBConnection;
import vds.UI.SystemAdmin.SysAdminMainFrame;



/**
 *
 * @author 17327
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    DBConnection conn;
    Connection sqlConn;
    Resultset rs;
    PreparedStatementWrapper pst = null;

    public SignUpForm() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DBConnection();
        sqlConn = DBConnection.connectDB();
        System.out.println("Urole from admin page" + SysAdminMainFrame.Urole);
        if (conn == null) {
            JOptionPane.showMessageDialog(this,
                    "Database Error", "Failure", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fNameFeild = new javax.swing.JTextField();
        countryFeild = new javax.swing.JTextField();
        lNameFeild = new javax.swing.JTextField();
        emailFeild = new javax.swing.JTextField();
        contactFeild = new javax.swing.JTextField();
        femaleRadio = new javax.swing.JRadioButton();
        maleRadio = new javax.swing.JRadioButton();
        dobDate = new com.toedter.calendar.JDateChooser();
        signInBtn = new javax.swing.JButton();
        signUpBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        ageFeild = new javax.swing.JTextField();
        cityFeild = new javax.swing.JTextField();
        stateFeild = new javax.swing.JTextField();
        countryFeild1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fNameFeild.setBackground(new java.awt.Color(97, 212, 195));
        fNameFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fNameFeild.setForeground(new java.awt.Color(36, 47, 65));
        fNameFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fNameFeild.setText("First Name");
        fNameFeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        fNameFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNameFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNameFeildFocusLost(evt);
            }
        });
        fNameFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNameFeildMouseClicked(evt);
            }
        });
        fNameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameFeildActionPerformed(evt);
            }
        });
        jPanel1.add(fNameFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 40));

        countryFeild.setBackground(new java.awt.Color(97, 212, 195));
        countryFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countryFeild.setForeground(new java.awt.Color(36, 47, 65));
        countryFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        countryFeild.setText("Country");
        countryFeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        countryFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFeildFocusLost(evt);
            }
        });
        countryFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryFeildMouseClicked(evt);
            }
        });
        countryFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryFeildActionPerformed(evt);
            }
        });
        jPanel1.add(countryFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, 40));

        lNameFeild.setBackground(new java.awt.Color(97, 212, 195));
        lNameFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lNameFeild.setForeground(new java.awt.Color(36, 47, 65));
        lNameFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lNameFeild.setText("Last Name");
        lNameFeild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 47, 65)));
        lNameFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lNameFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lNameFeildFocusLost(evt);
            }
        });
        lNameFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lNameFeildMouseClicked(evt);
            }
        });
        lNameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameFeildActionPerformed(evt);
            }
        });
        jPanel1.add(lNameFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, 40));

        emailFeild.setBackground(new java.awt.Color(97, 212, 195));
        emailFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailFeild.setForeground(new java.awt.Color(36, 47, 65));
        emailFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailFeild.setText("Email");
        emailFeild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 47, 65)));
        emailFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFeildFocusLost(evt);
            }
        });
        emailFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFeildMouseClicked(evt);
            }
        });
        emailFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFeildActionPerformed(evt);
            }
        });
        jPanel1.add(emailFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 40));

        contactFeild.setBackground(new java.awt.Color(97, 212, 195));
        contactFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactFeild.setForeground(new java.awt.Color(36, 47, 65));
        contactFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contactFeild.setText("Contact");
        contactFeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        contactFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFeildFocusLost(evt);
            }
        });
        contactFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactFeildMouseClicked(evt);
            }
        });
        contactFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFeildActionPerformed(evt);
            }
        });
        jPanel1.add(contactFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, 40));

        femaleRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        femaleRadio.setForeground(new java.awt.Color(36, 47, 65));
        femaleRadio.setText("Female");
        femaleRadio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        femaleRadio.setIconTextGap(15);
        jPanel1.add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 90, -1));

        maleRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maleRadio.setForeground(new java.awt.Color(36, 47, 65));
        maleRadio.setText("Male");
        maleRadio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        maleRadio.setIconTextGap(15);
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });
        jPanel1.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, -1));

        dobDate.setBackground(new java.awt.Color(97, 212, 195));
        dobDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date of Birth", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(36, 47, 65))); // NOI18N
        dobDate.setForeground(new java.awt.Color(36, 47, 65));
        jPanel1.add(dobDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, -1));

        signInBtn.setBackground(new java.awt.Color(97, 212, 195));
        signInBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(32, 47, 65));
        signInBtn.setText("Sign In");
        signInBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 47, 65), 1, true));
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 90, 40));

        signUpBtn.setBackground(new java.awt.Color(97, 212, 195));
        signUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(32, 47, 65));
        signUpBtn.setText("Sign Up");
        signUpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 47, 65), 1, true));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 90, 40));

        passwordField.setBackground(new java.awt.Color(97, 212, 195));
        passwordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(36, 47, 65));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("Password");
        passwordField.setToolTipText("");
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        passwordField.setEchoChar('\u0000');
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 40));

        ageFeild.setBackground(new java.awt.Color(97, 212, 195));
        ageFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageFeild.setForeground(new java.awt.Color(36, 47, 65));
        ageFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ageFeild.setText("Age");
        ageFeild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 47, 65)));
        ageFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFeildFocusLost(evt);
            }
        });
        ageFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageFeildMouseClicked(evt);
            }
        });
        ageFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFeildActionPerformed(evt);
            }
        });
        jPanel1.add(ageFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 170, 40));

        cityFeild.setBackground(new java.awt.Color(97, 212, 195));
        cityFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cityFeild.setForeground(new java.awt.Color(36, 47, 65));
        cityFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cityFeild.setText("City");
        cityFeild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 47, 65)));
        cityFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFeildFocusLost(evt);
            }
        });
        cityFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cityFeildMouseClicked(evt);
            }
        });
        cityFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFeildActionPerformed(evt);
            }
        });
        jPanel1.add(cityFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 170, 40));

        stateFeild.setBackground(new java.awt.Color(97, 212, 195));
        stateFeild.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stateFeild.setForeground(new java.awt.Color(36, 47, 65));
        stateFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stateFeild.setText("State");
        stateFeild.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        stateFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateFeildFocusLost(evt);
            }
        });
        stateFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateFeildMouseClicked(evt);
            }
        });
        stateFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateFeildActionPerformed(evt);
            }
        });
        jPanel1.add(stateFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, 40));

        countryFeild1.setBackground(new java.awt.Color(97, 212, 195));
        countryFeild1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countryFeild1.setForeground(new java.awt.Color(36, 47, 65));
        countryFeild1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        countryFeild1.setText("Country");
        countryFeild1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 47, 65), 1, true));
        countryFeild1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryFeild1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFeild1FocusLost(evt);
            }
        });
        countryFeild1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryFeild1MouseClicked(evt);
            }
        });
        countryFeild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryFeild1ActionPerformed(evt);
            }
        });
        jPanel1.add(countryFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, 40));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setForeground(new java.awt.Color(97, 212, 195));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/injection.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 212, 195));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vaccine Matrix");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 212, 195), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFeildFocusGained
        if (fNameFeild.getText().equals("First Name")) {
            fNameFeild.setText(null);
            fNameFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_fNameFeildFocusGained

    private void fNameFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFeildFocusLost
        if (fNameFeild.getText().length() == 0) {
            fNameFeild.setText("First Name");
            //            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_fNameFeildFocusLost

    private void fNameFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFeildMouseClicked

    private void fNameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFeildActionPerformed

    private void lNameFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lNameFeildFocusGained
        if (lNameFeild.getText().equals("Last Name")) {
            lNameFeild.setText(null);
            lNameFeild.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameFeildFocusGained

    private void lNameFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lNameFeildFocusLost
        if (lNameFeild.getText().length() == 0) {
            lNameFeild.setText("Last Name");

        }   // TODO add your handling code here:
    }//GEN-LAST:event_lNameFeildFocusLost

    private void lNameFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNameFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameFeildMouseClicked

    private void lNameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameFeildActionPerformed

    private void contactFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFeildFocusGained
        if (contactFeild.getText().equals("Contact")) {
            contactFeild.setText(null);
            contactFeild.requestFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_contactFeildFocusGained

    private void contactFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFeildFocusLost
        if (contactFeild.getText().length() == 0) {
            contactFeild.setText("Contact");
        }// TODO add your handling code here:
    }//GEN-LAST:event_contactFeildFocusLost

    private void contactFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFeildMouseClicked

    private void contactFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFeildActionPerformed

    private void emailFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFeildFocusGained
        if (emailFeild.getText().equals("Email")) {
            emailFeild.setText(null);
            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_emailFeildFocusGained

    private void emailFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFeildFocusLost
        if (emailFeild.getText().length() == 0) {
            emailFeild.setText("Email");
            //            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_emailFeildFocusLost

    private void emailFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeildMouseClicked

    private void emailFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeildActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed

        SignInForm sr = new SignInForm();
        sr.setVisible(true);
        super.dispose();
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_signInBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        String role = SysAdminMainFrame.Urole;
        if (role == null) {
            role = MainFrame.role;
        }
        System.out.println("in sign up"+role);
        String fName = fNameFeild.getText();
        String lName = lNameFeild.getText();
        String email = emailFeild.getText();
        String contact = contactFeild.getText();
        String age = ageFeild.getText();
        String password = new String(passwordField.getPassword());
        String gender = maleRadio.isSelected() ? (gender = "Male") : (gender = "Female");
        String city = cityFeild.getText();
        String state = stateFeild.getText();
        String country = countryFeild.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(dobDate.getDate());
        String emailPattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        String phonePattern = "(0|91)?[6-9][0-9]{9}";

        String namePattern = "[a-zA-Z_ ]+";

        String passwordPattern = "^(?=.*[0-9])"
                + "(?=.*[a-z])(?=.*[A-Z])"
                + "(?=.*[@#$%^&+=])"
                + "(?=\\S+$).{8,20}$";

        if (!fName.matches(namePattern) && !lName.matches(namePattern)) {
            JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (date.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this, "Enter a Valid Email", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!contact.matches(phonePattern)) {
            JOptionPane.showMessageDialog(this, "Enter a Valid Phone Number", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!password.matches(passwordPattern)) {
            JOptionPane.showMessageDialog(this, "Password should contain atleast 1 special character and number", "Warning",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            
                if(role.equals("Patient")){
                    Patient p = new Patient(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else if(role.equals("HospitalAdmin")){
                    HospitalAdmin p = new HospitalAdmin(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
     
                    p.addToDB();
                }else if(role.equals("ClinicAdmin")){
                    ClinicAdmin p = new ClinicAdmin(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else if(role.equals("NgoAdmin")){
                    NgoAdmin p = new NgoAdmin(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else if(role.equals("SystemAdmin")){
                    SystemAdmin p = new SystemAdmin(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else if(role.equals("SupplierAdmin")){
                    SupplyManager p = new SupplyManager(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else if(role.equals("EnterpriseAdmin")){
                    EnterpriseManager p = new EnterpriseManager(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else if(role.equals("DistributorAdmin")){
                    DistributingManager p = new DistributingManager(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }else{
                    LogisticsManager p = new LogisticsManager(fName,lName,email,contact,Integer.parseInt(age),city,state,country,password,gender,date,role);
                    p.addToDB();
                }
                
                JOptionPane.showMessageDialog(this, "Registration Successfull", "Welcome",
                        JOptionPane.INFORMATION_MESSAGE);
                SignInForm sr = new SignInForm();
                sr.setVisible(true);
                super.dispose();
                this.setVisible(false);
             

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpBtnActionPerformed

    

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (passwordField.getText().equals("Password")) {
            passwordField.setText("");
            passwordField.requestFocus();
            passwordField.setEchoChar('*');
        }// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (passwordField.getText().length() == 0) {
            passwordField.setText("Password");
            passwordField.setEchoChar('\u0000');
        }// TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void ageFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFeildFocusGained
        if (ageFeild.getText().equals("Age")) {
            ageFeild.setText(null);
            ageFeild.requestFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_ageFeildFocusGained

    private void ageFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFeildFocusLost
        if (ageFeild.getText().length() == 0) {
            ageFeild.setText("Age");
            //            emailFeild.requestFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_ageFeildFocusLost

    private void ageFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFeildMouseClicked

    private void ageFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFeildActionPerformed

    private void cityFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFeildFocusGained
        if (cityFeild.getText().equals("City")) {
            cityFeild.setText(null);
            cityFeild.requestFocus();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_cityFeildFocusGained

    private void cityFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFeildFocusLost
        if (cityFeild.getText().length() == 0) {
            cityFeild.setText("City");
            //            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_cityFeildFocusLost

    private void cityFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cityFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFeildMouseClicked

    private void cityFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFeildActionPerformed

    private void stateFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFeildFocusGained
        if (stateFeild.getText().equals("State")) {
            stateFeild.setText(null);
            stateFeild.requestFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_stateFeildFocusGained

    private void stateFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFeildFocusLost
        if (stateFeild.getText().length() == 0) {
            stateFeild.setText("State");
            //            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_stateFeildFocusLost

    private void stateFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stateFeildMouseClicked

    private void stateFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateFeildActionPerformed

    private void countryFeild1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFeild1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFeild1FocusGained

    private void countryFeild1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFeild1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFeild1FocusLost

    private void countryFeild1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryFeild1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFeild1MouseClicked

    private void countryFeild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryFeild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFeild1ActionPerformed

    private void countryFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFeildActionPerformed

    private void countryFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFeildMouseClicked

    private void countryFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFeildFocusLost
        if (countryFeild.getText().length() == 0) {
            countryFeild.setText("Country");
            //            emailFeild.requestFocus();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_countryFeildFocusLost

    private void countryFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFeildFocusGained
        if (countryFeild.getText().equals("Country")) {
            countryFeild.setText(null);
            countryFeild.requestFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_countryFeildFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageFeild;
    private javax.swing.JTextField cityFeild;
    private javax.swing.JTextField contactFeild;
    private javax.swing.JTextField countryFeild;
    private javax.swing.JTextField countryFeild1;
    private com.toedter.calendar.JDateChooser dobDate;
    private javax.swing.JTextField emailFeild;
    private javax.swing.JTextField fNameFeild;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lNameFeild;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JTextField stateFeild;
    // End of variables declaration//GEN-END:variables
}
