package vds.UI;

import com.mysql.cj.jdbc.PreparedStatementWrapper;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vds.Business.Role.ClinicAdmin.ClinicAdmin;
import vds.Business.Role.DistributingManager.DistributingManager;
import vds.Business.Role.EnterpriseManager.EnterpriseManager;
import vds.Business.Role.HospitalAdmin.HospitalAdmin;
import vds.Business.Role.NgoAdmin.NgoAdmin;
import vds.Business.Role.Patient.Patient;
import vds.Business.Role.SupplyManager.SupplyManager;
import vds.Business.Role.SystemAdmin;
import vds.Business.UserAccount.UserAccount;
import vds.Database.DBConnection;
import vds.UI.Clinic.ClinicMainFrame;
import vds.UI.Distributor.DistributorMainFrame;
import vds.UI.Enterprise.EnterpriseMainFrame;
import vds.UI.Hospital.HospitalMainFrame;
import vds.UI.NGO.NGOMainFrame;
import vds.UI.Patient.PatientMainFrame;
import vds.UI.Supplier.SupplierMainFrame;
import vds.UI.SystemAdmin.SysAdminMainFrame;

public class SignInForm extends javax.swing.JFrame {

    /**
     * Creates new form SignInForm
     */
    DBConnection conn;
    Connection sqlConn;
    Resultset rs;
    PreparedStatementWrapper pst = null;
    public static String Urole;
    public static String userFullName;
    public static String userEmail;
    public static String userContact;

    public SignInForm() {
        initComponents();
        setLocationRelativeTo(null);
        conn = new DBConnection();
        sqlConn = DBConnection.connectDB();

        if (conn == null) {
            JOptionPane.showMessageDialog(this,
                    "Database Error", "Failure", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        emailFeild = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/injection.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 270, 270));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 47, 65));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vaccine Matrix");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 47, 65), 1, true));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 240, 68));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailFeild.setBackground(new java.awt.Color(36, 47, 65));
        emailFeild.setForeground(new java.awt.Color(255, 255, 255));
        emailFeild.setText("Email");
        emailFeild.setBorder(null);
        emailFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFeildFocusLost(evt);
            }
        });
        emailFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFeildMouseClicked(evt);
            }
        });
        emailFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFeildActionPerformed(evt);
            }
        });
        jPanel2.add(emailFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 40));

        passwordField.setBackground(new java.awt.Color(36, 47, 65));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("Password");
        passwordField.setToolTipText("");
        passwordField.setBorder(null);
        passwordField.setEchoChar('\u0000');
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 260, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 40));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locked (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (1).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 40, 30));

        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeildActionPerformed

    private void emailFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFeildFocusGained
        if (emailFeild.getText().equals("Email")) {
            emailFeild.setText(null);
            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_emailFeildFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (passwordField.getText().equals("Password")) {
            passwordField.setText("");
            passwordField.requestFocus();
            passwordField.setEchoChar('*');
        }// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusGained

    private void emailFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFeildFocusLost
        if (emailFeild.getText().length() == 0) {
            emailFeild.setText("Email");
//            emailFeild.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_emailFeildFocusLost

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (passwordField.getText().length() == 0) {
            passwordField.setText("Password");
            passwordField.setEchoChar('\u0000');
        }// TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusLost

    private void emailFeildMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFeildMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFeildMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = emailFeild.getText();
        String role = MainFrame.role;
        System.out.println(role);
        String emailPattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        String password = new String(passwordField.getPassword());
        if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Enter Correct Email ID", "Sign-In", 2);
        } else if (emailFeild.getText().isEmpty() && passwordField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Enter All Details", "Sign-In", 2);
        } else {
            if (role.equals("SysAdmin")) {
                SystemAdmin sa = new SystemAdmin(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        SysAdminMainFrame nl = new  SysAdminMainFrame ();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (role.equals("Patient")) {
                Patient sa = new Patient(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        PatientMainFrame nl = new  PatientMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (role.equals("HospitalAdmin")) {
                HospitalAdmin sa = new HospitalAdmin(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        HospitalMainFrame nl = new  HospitalMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else if (role.equals("ClinicAdmin")) {
                ClinicAdmin sa = new ClinicAdmin(email, password, role);
                try {
                   sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        ClinicMainFrame nl = new  ClinicMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            } else if (role.equals("NgoAdmin")) {
                NgoAdmin sa = new NgoAdmin(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        NGOMainFrame nl = new  NGOMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            } else if (role.equals("EnterpriseAdmin")) {
                EnterpriseManager sa = new EnterpriseManager(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        EnterpriseMainFrame nl = new  EnterpriseMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else if (role.equals("DistributorAdmin")) {
                DistributingManager sa = new DistributingManager(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        DistributorMainFrame nl = new  DistributorMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            } else if (role.equals("SupplierAdmin")) {
                SupplyManager sa = new SupplyManager(email, password, role);
                try {
                    sa.checkValidUser();
                    userFullName = UserAccount.userFullName;
                    userEmail = UserAccount.userEmail;
                    userContact = UserAccount.userContact;
                    if (userFullName == null) {
                        JOptionPane.showMessageDialog(this, "Enter correct details", "Warning",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login SuccessFull", "Welcome",
                                JOptionPane.INFORMATION_MESSAGE);
                        SignInForm mf = new SignInForm();
                        SupplierMainFrame nl = new  SupplierMainFrame();
                        mf.setVisible(false);
                        nl.setVisible(true);
                        super.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SignInForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Other Role", "Warning", 2);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SignUpForm sr = new SignUpForm();
        Urole = MainFrame.role;
        sr.setVisible(true);
        super.dispose();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SignInForm sf = new SignInForm();
        MainFrame mf = new MainFrame();
        sf.setVisible(false);
        mf.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailFeild;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
